spring.application.name=sistema-hr

# 1. O Endere\u00e7o do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_hr

# 2. As Credenciais de Acesso

spring.datasource.username=root
spring.datasource.password=Brunin$16

# 3. A M\u00e1gica do Hibernate (Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update

